"use client";

import Image from "next/image";
import Link from "next/link";

const JURUSAN = ["TJKT", "PPLG", "Pemasaran", "DKV", "MPLB"];
const ROLES = [
  ["Guru", "Mengatur materi, tugas, asesmen, dan penilaian untuk kelas yang diampu."],
  ["Siswa", "Mengakses pembelajaran, mengumpulkan pekerjaan, dan melihat perkembangan belajar."],
  ["Kepsek", "Memantau aktivitas pembelajaran dan laporan akademik untuk pengambilan keputusan."],
  ["Kurikulum", "Mengawasi pelaksanaan pembelajaran serta mengevaluasi laporan nilai."],
  ["Admin", "Mengelola data pengguna, kelas, jurusan, mata pelajaran, dan hak akses."],
] as const;
const FEATURES = [
  ["Materi pembelajaran", "Bagikan PDF dan tautan materi agar dapat diakses kapan saja."],
  ["Tugas & asesmen", "Buat tugas, kuis, atau ujian dan kumpulkan jawaban dalam satu tempat."],
  ["Penilaian", "Kelola nilai berdasarkan mata pelajaran, kelas, dan hasil belajar siswa."],
  ["Manajemen akademik", "Satukan data guru, siswa, kelas, jurusan, dan mata pelajaran."],
] as const;

function ArrowIcon() {
  return <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true" className="h-4 w-4"><path d="M4 10h11M11 5l5 5-5 5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

export default function Home() {
  return (
    <div className="min-h-screen bg-[#fcfcfd] text-[#182033]" style={{ fontFamily: "var(--font-geist-sans), Arial, sans-serif" }}>
      <header className="sticky top-0 z-50 border-b border-[#e8ebf2] bg-white/95 backdrop-blur-sm">
        <div className="mx-auto flex h-[68px] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
          <a href="#beranda" className="flex shrink-0 items-center gap-2.5" aria-label="Classify beranda"><Image src="/Logo1.png" alt="" width={32} height={32} className="rounded-[9px] object-contain" /><span className="text-[17px] font-bold tracking-[-0.04em]">Classify</span></a>
          <nav className="hidden items-center gap-6 text-sm font-medium text-[#697386] lg:flex" aria-label="Navigasi utama"><a href="#tentang" className="hover:text-[#6B85F6]">Tentang</a><a href="#system" className="hover:text-[#6B85F6]">Sistem</a><a href="#role" className="hover:text-[#6B85F6]">Peran</a><a href="#jurusan" className="hover:text-[#6B85F6]">Jurusan</a><a href="#contact" className="hover:text-[#6B85F6]">Kontak</a></nav>
          <Link href="/login" className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-[#6B85F6] px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-[#5974ed]">Masuk <ArrowIcon /></Link>
        </div>
      </header>

      <main>
        <section id="beranda" className="overflow-hidden border-b border-[#e8ebf2] bg-white">
          <div className="mx-auto grid max-w-7xl gap-12 px-4 py-14 sm:px-6 md:py-20 lg:grid-cols-[.94fr_1.06fr] lg:items-center lg:gap-16 lg:px-8 lg:py-24">
            <div className="max-w-xl"><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#6B85F6]"><span className="h-2 w-2 rounded-full bg-[#6B85F6]" /> Learning management system</p><h1 className="text-4xl font-bold tracking-[-.055em] sm:text-5xl lg:text-[56px] lg:leading-[1.04]">Pembelajaran sekolah, lebih terarah dalam satu sistem.</h1><p className="mt-6 max-w-lg text-[15px] leading-7 text-[#657084] sm:text-base">Classify menyatukan materi, tugas, asesmen, penilaian, dan pemantauan akademik agar setiap peran dapat bekerja dengan lebih jelas.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-lg bg-[#6B85F6] px-5 py-3 text-sm font-semibold text-white hover:bg-[#5974ed]">Mulai dengan Classify <ArrowIcon /></Link><a href="#tentang" className="rounded-lg border border-[#dce1eb] px-5 py-3 text-sm font-semibold text-[#3f4a5e] hover:bg-[#f8f9ff]">Pelajari sistemnya</a></div><div className="mt-10 grid max-w-md grid-cols-3 divide-x divide-[#e5e8ef] border-y border-[#e5e8ef] py-4">{[["5", "Peran terhubung"], ["4", "Fitur inti"], ["1", "Sistem terpadu"]].map(([value, label]) => <div key={label} className="px-3 first:pl-0"><p className="text-xl font-bold tracking-[-.04em]">{value}</p><p className="mt-1 text-[11px] leading-4 text-[#7b8495]">{label}</p></div>)}</div></div>
            <DashboardPreview />
          </div>
        </section>

        <section id="tentang" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="grid gap-8 lg:grid-cols-[.86fr_1.14fr] lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#6B85F6]">Tentang Classify</p><h2 className="mt-3 text-3xl font-bold tracking-[-.045em] sm:text-4xl">Satu tempat untuk proses belajar yang saling terhubung.</h2></div><div className="grid gap-4 sm:grid-cols-2"><p className="text-[15px] leading-7 text-[#647084]">Classify adalah LMS berbasis web yang membantu sekolah mengelola kegiatan belajar mengajar secara digital, terstruktur, dan efisien.</p><div className="border-l-2 border-[#6B85F6] pl-4 text-sm leading-6 text-[#465166]">Dirancang untuk menghubungkan guru, siswa, manajemen sekolah, serta data akademik dalam satu sistem.</div></div></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Materi yang mudah diakses", "Guru membagikan bahan belajar kapan pun diperlukan."], ["Evaluasi yang rapi", "Tugas, asesmen, jawaban, dan nilai tidak lagi tersebar."], ["Keputusan berbasis data", "Laporan memberi gambaran perkembangan belajar yang jelas."]].map(([title, description], i) => <article key={title} className={`border border-[#e3e7ef] p-5 ${i === 0 ? "bg-[#f5f6ff]" : "bg-white"}`}><span className="text-xs font-bold text-[#6B85F6]">0{i + 1}</span><h3 className="mt-8 font-bold tracking-[-.025em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6f798a]">{description}</p></article>)}</div></section>

        <section id="system" className="border-y border-[#e6e9f0] bg-[#f7f8fb]"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#6B85F6]">Sistem terintegrasi</p><h2 className="mt-3 text-3xl font-bold tracking-[-.045em] sm:text-4xl">Dari kelas hingga laporan akademik.</h2></div><p className="max-w-md text-sm leading-6 text-[#6d7788]">Setiap modul dibuat untuk menjaga proses pembelajaran tetap berjalan, terbaca, dan mudah ditindaklanjuti.</p></div><div className="mt-10 grid gap-3 md:grid-cols-2"><article className="min-h-56 border border-[#dfe4ef] bg-[#6B85F6] p-6 text-white md:row-span-2"><span className="text-xs font-bold tracking-[.16em] text-white/70">ALUR UTAMA</span><h3 className="mt-16 max-w-sm text-2xl font-bold tracking-[-.04em]">Kelola pembelajaran tanpa berpindah-pindah tempat.</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/80">Materi, aktivitas siswa, dan hasil belajar tersedia dalam konteks yang sama.</p></article>{FEATURES.map(([title, description], index) => <article key={title} className="border border-[#dfe4ef] bg-white p-6"><span className="text-xs font-bold text-[#6B85F6]">0{index + 1}</span><h3 className="mt-6 font-bold tracking-[-.025em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6f798a]">{description}</p></article>)}</div></div></section>

        <section id="role" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#6B85F6]">Dibuat untuk setiap peran</p><h2 className="mt-3 text-3xl font-bold tracking-[-.045em] sm:text-4xl">Akses yang sesuai, informasi yang relevan.</h2></div><div className="mt-10 grid border-l border-t border-[#e1e5ed] sm:grid-cols-2 lg:grid-cols-5">{ROLES.map(([name, description], index) => <article key={name} className="min-h-56 border-b border-r border-[#e1e5ed] bg-white p-5 hover:bg-[#f6f7ff]"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#6B85F6]">0{index + 1}</span><span className="h-2 w-2 rounded-full bg-[#d7defd]" /></div><h3 className="mt-16 text-lg font-bold tracking-[-.03em]">{name}</h3><p className="mt-2 text-sm leading-6 text-[#707a8b]">{description}</p></article>)}</div></section>

        <section id="jurusan" className="border-y border-[#e6e9f0] bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 md:grid-cols-[.85fr_1.15fr] lg:px-8 lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#6B85F6]">Lingkup pembelajaran</p><h2 className="mt-3 text-3xl font-bold tracking-[-.045em]">Ruang untuk setiap jurusan berkembang.</h2><p className="mt-4 text-sm leading-6 text-[#6d7788]">Classify mendukung struktur belajar lintas jurusan dalam satu lingkungan sekolah.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{JURUSAN.map((major, index) => <div key={major} className={`flex min-h-28 items-end border p-4 text-sm font-bold tracking-[-.025em] ${index === 0 ? "border-[#6B85F6] bg-[#6B85F6] text-white" : "border-[#e1e5ed] bg-[#fafbfc]"}`}>{major}</div>)}</div></div></section>

        <section id="contact" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="grid overflow-hidden border border-[#dfe4ef] lg:grid-cols-[.85fr_1.15fr]"><div className="bg-[#6B85F6] p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-white/70">Kontak</p><h2 className="mt-3 text-3xl font-bold tracking-[-.045em]">Mari terhubung.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-white/80">Punya pertanyaan tentang Classify atau ingin mendiskusikan penerapannya di sekolah?</p><div className="mt-12 space-y-5 border-t border-white/20 pt-6 text-sm"><div><p className="text-xs text-white/65">Telepon</p><p className="mt-1 font-semibold">+62-838-7127-4193</p></div><div><p className="text-xs text-white/65">Email</p><p className="mt-1 break-words font-semibold">dhanitriadisaputra@gmail.com</p></div></div></div><div className="relative min-h-[300px] bg-[#edf0f5]"><Image src="/foto-kontak.png" alt="Kontak Classify" fill sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover" /></div></div></section>
      </main>

      <footer className="border-t border-[#e5e8ef] bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 md:grid-cols-[1.3fr_.7fr_.9fr] lg:px-8"><div><div className="flex items-center gap-2"><Image src="/Logo1.png" alt="" width={28} height={28} className="rounded-[8px]" /><span className="font-bold tracking-[-.03em]">Classify</span></div><p className="mt-4 max-w-xs text-sm leading-6 text-[#6e7889]">Platform pembelajaran digital untuk sekolah yang lebih rapi, terarah, dan terintegrasi.</p></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#8b94a4]">Navigasi</p><div className="mt-4 grid gap-2 text-sm text-[#586376]"><a href="#tentang">Tentang</a><a href="#system">Sistem</a><a href="#role">Peran</a><Link href="/login">Masuk</Link></div></div><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#8b94a4]">Temukan kami</p><div className="mt-4 space-y-2 text-sm text-[#586376]"><p>Instagram · @chronion999</p><p>GitHub · Dhanidev-838</p><p>LinkedIn · Dhani Triadi Saputra</p></div></div></div><div className="border-t border-[#e9ecf2] py-5 text-center text-xs text-[#8b94a4]">© 2026 Classify. All rights reserved.</div></footer>
    </div>
  );
}

function DashboardPreview() {
  const progress = [["Tugas Matematika", 78], ["Materi Pemrograman", 64], ["Asesmen Bahasa", 45]];
  return <div className="relative mx-auto w-full max-w-[610px] lg:mx-0"><div className="absolute -right-8 top-9 hidden h-44 w-44 rounded-full bg-[#eef1ff] lg:block" /><div className="relative overflow-hidden rounded-xl border border-[#dfe4ef] bg-white p-3 shadow-[0_20px_60px_-36px_rgba(43,59,110,.45)] sm:p-4"><div className="flex items-center justify-between border-b border-[#edf0f5] pb-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#6B85F6]" /><span className="text-xs font-semibold text-[#465166]">Ringkasan pembelajaran</span></div><span className="rounded-md bg-[#f2f4ff] px-2 py-1 text-[10px] font-bold text-[#6078e9]">September 2026</span></div><div className="grid gap-3 pt-3 sm:grid-cols-[1.2fr_.8fr]"><div className="rounded-lg border border-[#e7eaf1] p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-[#637086]">Aktivitas kelas</p><p className="mt-2 text-2xl font-bold tracking-[-.05em]">24 <span className="text-xs font-medium text-[#7d8797]">aktif</span></p></div><span className="rounded-md bg-[#e9edff] p-2 text-xs font-bold text-[#6B85F6]">✓</span></div><div className="mt-5 space-y-3">{progress.map(([item, value]) => <div key={item}><div className="flex justify-between text-[10px] text-[#7a8494]"><span>{item}</span><span>{value}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#edf0f5]"><div className="h-full rounded-full bg-[#6B85F6]" style={{ width: `${value}%` }} /></div></div>)}</div></div><div className="rounded-lg bg-[#6B85F6] p-4 text-white"><p className="text-xs font-semibold text-white/75">Perlu perhatian</p><p className="mt-4 text-3xl font-bold tracking-[-.06em]">06</p><p className="mt-1 text-[11px] leading-4 text-white/80">Tugas menunggu penilaian hari ini.</p><div className="mt-7 border-t border-white/20 pt-3 text-[10px] font-semibold">Lihat detail →</div></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-lg border border-[#e7eaf1] px-4 py-3"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#8992a2]">Materi dibagikan</p><p className="mt-1 text-lg font-bold">128</p></div><div className="rounded-lg border border-[#e7eaf1] px-4 py-3"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#8992a2]">Partisipasi siswa</p><p className="mt-1 text-lg font-bold">92%</p></div></div></div></div>;
}
